name: pr-master

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install dependencies 📦
        run: npm install

      - name: Run linter 👀
        run: npm run lint-fix

      - name: Run tests 🧪
        run: npm run test:unit-coverage --if-present
